{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mandala-worker-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mandala.labels" . | nindent 4 }}
    app: mandala-worker
spec:
  selector:
    app: mandala-worker
  ports:
  - port: 9090
    targetPort: 9090
    name: metrics
{{- end }}
